### ISSUE TITLE
Old reference to `operator()`

### ISSUE THREAD

**Issue by scotchi** [NoAvailableAlias/nano-signal-slot#11]
Wouldn't the following patch now be correct?

    diff --git a/nano_function.hpp b/nano_function.hpp
    index 4a3cfe5..3a5925a 100644
    --- a/nano_function.hpp
    +++ b/nano_function.hpp
    @@ -51,7 +51,7 @@ public:
         static inline Function bind(L* pointer)
         {
             return { pointer, [](void *this_ptr, Args... args)
    -            { return (static_cast<L*>(this_ptr)->operator()(std::forward<Args>(args)...)); }};
    +            { return (static_cast<L*>(this_ptr)->emit(std::forward<Args>(args)...)); }};
         }
         inline operator DelegateKey() const
         {

**Comment by NoAvailableAlias** [comment]
The patch has been closed.

This signature of Nano::Function::bind is for binding to function objects (objects that define a suitable operator()). Changing this particular bind function won't work because function objects do not implement emit.

**Comment by scotchi** [comment]
What I was trying to work around was the fact that it used to be possible to chain signals, but now is no longer possible without defining `NANO_USE_DEPRECATED`.

The following minimal test case shows the issue (doesn't compile):

    #include <iostream>
    
    #define NANO_ALLOW_FUNCTION_OBJECTS
    // #define NANO_USE_DEPRECATED
    #include "../nano_signal_slot.hpp"
    
    using namespace Nano;
    
    static void foo()
    {
        std::cout << "foo" << std::endl;
    }
    
    int main()
    {
        Signal<void()> first;
        Signal<void()> second;
    
        first.connect(second);
        second.connect<foo>();
    
        first.emit();
    
        return 0;
    }

In non-trivial applications, chaining signals is often quite useful (and is a pretty standard feature of signal-slot implementations).

**Comment by NoAvailableAlias** [comment]
Hmm, I don't particularly like the idea of chaining signals as there are possibilities of infinite loops. However, the old operator() method does not use universal references because of signature conflicts with the old operator() accumulate. I would propose enhancing the old operator() emit to use universal references, removing the old operator() accumulate and replacing that with a named "accumulate" method. The problem is this would mean the emit interface would be changed yet again.

I'll add this change to the FT branch next time I have.
